branches:
	only:
		- master
sudo: required
language: php
php:
	- '5.6'
script: 
	- wget -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar
	- sh tests/startServer.sh > /dev/null 2>&1 &
	- php phpunit.phar --bootstrap tests/bootstrap_autoload.php tests
notifications:
	email: false
