branches:
  only:
    - master
sudo: required
language: php
php:
  - '5.6'
  - '7.1'
  - '7.3'
install:
  - composer install
script:
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar
  - php phpunit.phar --bootstrap tests/bootstrap_autoload.php tests
notifications:
  email: false
